name: Reusable Deployment
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: Name of deployable artifact
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: The result of the deployment
        value: ${{ jobs.deploy.outputs.outcome }}
    # secrets:
    #   some-secret:
    #     required: false
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.step-result-id.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List Files
        run: ls
      - name: Deploy
        run: echo "Deploying..."
      - name: Set result output
        id: step-result-id
        run: echo "step-result=sucess" >> $GITHUB_OUTPUT
